version: "3.0"

services:
  smart_ruby_plug:
    image: "mathosk/smart_ruby_plug:v0.3.0_armv6"
    privileged: true
    restart: always
    network_mode: bridge
    volumes:
      - /data/smart_ruby_plug/config:/home/pi/smart_ruby_plug/config
      - /data/smart_ruby_plug/log:/home/pi/smart_ruby_plug/log
    tty: true