# Pull base image
FROM mathosk/rpi-ruby-3.1.2-ubuntu-aarch64:latest

MAINTAINER Martin Markech <martin.markech@matho.sk>

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    vim \
    wget \
    git \
    build-essential \
    locales \
    cron \
    bash \
    libcurl4 \
    libcurl4-openssl-dev \
    gcc \
    doxygen \
    cmake \
    gdb \
    sudo

RUN mkdir -p /home/ubuntu/smart_ruby_plug

WORKDIR /home/ubuntu/smart_ruby_plug

ARG RAILS_ENV

RUN wget https://github.com/Matho/smart_ruby_plug/archive/refs/tags/v0.1.0.beta.tar.gz && tar -xf v0.1.0.beta.tar.gz -C /home/ubuntu/smart_ruby_plug

ENV GEM_HOME="/home/ubuntu/smart_ruby_plug/smart_ruby_plug-0.1.0.beta/vendor/bundle"
ENV PATH $GEM_HOME/bin:$GEM_HOME/gems/bin:$PATH

RUN gem install bundler -v '~> 2.3.0'

RUN cd /home/ubuntu/smart_ruby_plug/smart_ruby_plug-0.1.0.beta && bundle install --clean --path vendor/bundle

RUN cd /home/ubuntu && wget https://github.com/Matho/smart_ruby_plug_c_binaries/releases/download/v0.1.0.beta/libsmart_plug_C.so.v0.1.0.beta_77865ad7af

RUN ln -s /home/ubuntu/libsmart_plug_C.so.v0.1.0.beta_77865ad7af /home/ubuntu/smart_ruby_plug/smart_ruby_plug-0.1.0.beta/lib/clibrary/libsmart_plug_C.so

RUN mkdir -p /home/ubuntu/smart_ruby_plug_docker && cd /home/ubuntu/smart_ruby_plug_docker

COPY . /home/ubuntu/smart_ruby_plug_docker

RUN /home/ubuntu/smart_ruby_plug_docker/files/install_c_libraries.sh

CMD cd /home/ubuntu/smart_ruby_plug/smart_ruby_plug-0.1.0.beta && bundle exec /home/ubuntu/smart_ruby_plug/smart_ruby_plug-0.1.0.beta/bin/smart_ruby_plug start
