timers:
  boot_countdown_timer: 300 # seconds

internet_provider:
  name: 'Starlink'

home_assistant_node:
  host: 'http://10.0.3.100:8123'
  name: 'Home Assistant'
  long_lived_token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkZTBmYzBlMWRiZTE0MzA3OWYzNDkxMDExNzIxZmU0YyIsImlhdCI6MTY1NzQ5MzI4MiwiZXhwIjoxOTcyODUzMjgyfQ._SsIsZGIyOSuu9zfWs-_-la-0SDL8cm-h6K8zvbT_mM'
  smart_plug_entity_id: 'switch.smart_zasuvka_1090'

smart_plug:
  name: 'Plug 1090'

ping:
  interval: 30 # seconds
  check_wifi: false
  check_internet: false

  urls:
    for_internet:
      - "8.8.8.8" # Google DNS
      - "8.8.4.4" # Google DNS
      - "1.1.1.1" # Cloudflare
    for_wifi:
      antennas:
        provider:
          -
            url: "10.0.3.3"
            name: 'UISP 1090'
          -
            url: "10.0.3.10"
            name: 'Wifi 1090'
          -
            url: "10.0.3.1"
            name: 'Router 1090'
        client:
          -
            url: "10.0.3.11"
            name: 'Wifi 1099'
          -
            url: "192.168.0.1"
            name: 'Router 1099'



